[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "postgresql"]

[build.nixpacksPlan.phases.install]
cmds = ["pip install -r requirements.txt"]

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && python create_admin.py && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
